distributable:
  url: https://github.com/expo/eas-cli/archive/refs/tags/v{{version.raw}}.tar.gz
  strip-components: 1

display-name: eas

versions:
  github: expo/eas-cli

dependencies:
  nodejs.org: ^16 || ^18 || ^20 || ^22

build:
  dependencies:
    python.org: ~3.10
    classic.yarnpkg.com: "*"
    linux:
      llvm.org: <17
  script:
    - mkdir -p "{{prefix}}"
    - npm_config_build_from_source=true yarn install

    - run: yarn build-ci
      working-directory: packages/eas-json/

    - yarn build-ci
    - cp -r * {{prefix}}

    - run:
        - ln -s ../packages/eas-cli/bin/run bin/eas
      working-directory: ${{prefix}}
  env:
    CC: clang
    CXX: clang++
    LD: clang

provides:
  - bin/eas

test:
  dependencies:
    nodejs.org: "*"
    eas.dev/eas-cli: "*"
  script:
    - eas
    - eas --help
    - eas --version 
